export const CURRENT_USER = 'CURRENT_USER';
export const CURRENT_USER_SUCCESS = 'CURRENT_USER_SUCCESS';
export const CURRENT_USER_FAILURE = 'CURRENT_USER_FAILURE';
export const CURRENT_USER_LOGOUT = 'CURRENT_USER_LOGOUT';
